# Server Configuration
server.port=8080


# Jackson Configuration
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false

# Logging Configuration
logging.level.com.screenshot=INFO
logging.level.com.microsoft.playwright=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Scraping Configuration
app.scraping.default-timeout=30000
app.scraping.max-wait-time=10000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=leandrobarreto.barreto@gmail.com
spring.mail.password=lkuhjpifzqowwcur
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email Notification Configuration
app.email.notification.recipient=admin@empresa.com